# Generated by Django 5.0.1 on 2024-01-21 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movements_played', models.IntegerField(default=0)),
                ('board', models.JSONField(default=list)),
                ('next_turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_turn', to='tttapp.player')),
                ('players', models.ManyToManyField(related_name='games_played', to='tttapp.player')),
                ('starting_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_started', to='tttapp.player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_won', to='tttapp.player')),
            ],
        ),
    ]
