# Generated by Django 5.0.1 on 2024-01-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tttapp', '0003_alter_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='dummy_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dummy_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
