# Generated by Django 5.0.1 on 2024-01-23 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tttapp', '0004_game_dummy_field_player_dummy_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='dummy_field',
        ),
        migrations.RemoveField(
            model_name='player',
            name='dummy_field',
        ),
    ]
